In [2]:
my_class=[1,2,3,4]

In [3]:
my_class=[1,2,3,4]

In [4]:
my_class

[1, 2, 3, 4]

In [5]:
import numpy as np


In [6]:
np.array(my_class)

array([1, 2, 3, 4])

In [8]:
arr= np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
ranarr= np.random.randint(0,50,10)
ranarr

array([49, 42,  9, 29, 11, 15, 17, 42, 21,  0])

In [11]:
np.random.randint?

In [12]:
arr.reshape(5,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [15]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [17]:
np.zeros((5,5)

SyntaxError: unexpected EOF while parsing (<ipython-input-17-09ca45ab6853>, line 1)

In [18]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [19]:
np.random.rand(5)

array([ 0.51815427,  0.81937204,  0.49730396,  0.52760326,  0.80673518])

In [20]:
np.random.randint(1,50,10)

array([13, 46, 43,  9, 17, 23,  2,  3, 32, 21])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.